object Versions {
  lazy val organization = "com.github.dpratt747"
  lazy val scala3Version = "3.2.2"
  lazy val circeVersion = "0.14.0"
  lazy val catsEffectVersion = "3.4.8"
  lazy val http4sVersion = "0.23.18"
  lazy val ironVersion = "2.0.0"
  lazy val doobieVersion = "1.0.0-RC1"
  lazy val pureConfigVersion = "0.17.2"
  lazy val log4catsVersion = "2.5.0"
  lazy val tsecVersion = "0.4.0"
  lazy val scalaTestVersion = "3.2.15"
  lazy val scalaTestCatsEffectVersion = "1.4.0"
  lazy val testContainerVersion = "1.17.6"
  lazy val logbackVersion = "1.4.6"
  lazy val slf4jVersion = "2.0.5"
  lazy val javaMailVersion = "1.6.2"
  lazy val scalacheckVersion = "1.17.0"
  lazy val scalaTestPlusVersion = "3.2.15.0"
}
